## Numpy Dayy 1


In [1]:
# list  --- heterogenous and homogenous
# store elements in non-continuous memory
a=[12,34,56]

In [3]:
!pip install numpy

In [7]:
# for calculatinf time
import time
import numpy as np
size=10000000

#for list 
a=list(range(size))
start_l=time.time()
a=list(map(lambda i : i**2,a))
end_l=time.time() - start_l

# array
a=np.arange(size)
start_a=time.time()
a=[a**2]
end_a=time.time() - start_a

print("Time taken by list",end_l)
print("Time taken by array",end_a)




Time taken by list 2.918133020401001
Time taken by array 0.033341407775878906


## Numpy day2

In [1]:
import numpy as np

# Array

In [ ]:
## how to create array ----- .array()

a=[12,34,56]
print(type(a))
print(a)

In [4]:
# array using list 
# it has datatype as numpy.ndarray

arr = np.array(a)
print(arr)
print(type(arr))

arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))

[12 34 56]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


## Array attribute**
#### jo cheej parameter accept kre vo function hote haii

#### 1) .ndim -- to check dimension of array and it is a attribue

In [8]:
arr = np.array(a)
print(arr)
print(arr.ndim)    # it shows the dimension of array

[12 34 56]
1


#### 2)  .shape -- it shows the number of rows and column

In [9]:
arr = np.array(a)
print(arr)
print(arr.shape)

[12 34 56]
(3,)


#### 3) .size--- it shows total no. of elemnt in the array

In [10]:
arr = np.array(a)
print(arr)
print(arr.size)

[12 34 56]
3


#### 4) .dtype ---  it shows the datatype of  elements  inside array 
#### if there is different datatype of elements in a array it converts whole array in the preferred datatype acc. to their preference

In [12]:
# string ka dtype --- <U49 ---- here 49 is string memory length and it changes usually and depends on different system--- u is unicode
arr1 = [12,13,14]
arr2=[12,13.7,18]
arr3=[12,17.8,'code']

arr1=np.array(arr1)
print(arr1)
print(arr1.dtype)
print(type(arr1))

arr2=np.array(arr2)
print(arr2)
print(arr2.dtype)
print(type(arr2))

arr3=np.array(arr3)
print(arr3)
print(arr3.dtype)
print(type(arr3))

[12 13 14]
int64
<class 'numpy.ndarray'>
[12.  13.7 18. ]
float64
<class 'numpy.ndarray'>
['12' '17.8' 'code']
<U32
<class 'numpy.ndarray'>


#### 5) .itemsize -- single element ka dataype kitni memory store kra hai vo btata hai

In [13]:
str_array = np.array(['12','34',45])
float_array = np.array([12.45,34,45])
int_array = np.array([12,17,20])

print(str_array)
print(str_array.itemsize)
print(float_array)
print(float_array.itemsize)
print(int_array)
print(int_array.itemsize)

['12' '34' '45']
84
[12.45 34.   45.  ]
8
[12 17 20]
8


In [16]:
arr1=np.array([1,2,3,4,5])
print((arr1.itemsize)*arr1.size)

40


# 1d_array using functions:


### 1) arange-- work same as range but name change for array it is a function of numpy
#### arange(start,end-1,step)

In [3]:
import numpy as np
arr1=np.array(np.arange(1,101))
print(arr1)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [5]:
arr1=np.array(np.arange(0,51,5))
print(arr1)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [6]:
arr1=np.array(np.arange(0,20,2))
print(arr1)

[ 0  2  4  6  8 10 12 14 16 18]


## automatically

In [1]:
import numpy as np

In [2]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
