# 2d Array


## How to create 2d array
### 2d array has only two element row and column
### ([[10,20],[20,30],[30,40]]) --- this is 2d array with 3 row and 2 column 
### when there is 2 square bracket it is 2d array 
### stores in the linear form in memory
#### n bracket means n number of dimension array

In [1]:
import numpy as np

In [2]:
# 3 row 2 column
arr2=np.array([[10,20],[20,30],[30,40]])
print(arr2)
print(arr2.size)
print(arr2.shape)

[[10 20]
 [20 30]
 [30 40]]
6
(3, 2)


In [5]:
# 3 by 3
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2.size)
print(arr2.shape)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
2


## 16/02/2026

## creating 2d Array using numpy function

## 1)Reshape -- used to make the shape of matrix of already existing elements made using arange
### syntax-- array_name.reshape(r,c) or arange().reshape(c,r)

In [1]:
import numpy as np

In [3]:
print(np.arange(1,10).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr2=np.arange(1,82).reshape(9,9)
print(arr2)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]]


## 2) Random -- it is a family and it has many childs 

### a) Random ---generates random values between 0 to 1 only floating values in which 0 and 1 are inclusive

In [5]:
# using random from random family
arr =np.random.random(10)
print(arr)

[0.63880999 0.47532822 0.43004224 0.48111389 0.77666294 0.87369023
 0.08473878 0.73758634 0.43742367 0.55988958]


In [8]:
# reshape with random
arr=np.random.random(20).reshape(5,4)
print(arr)

[[0.15911532 0.52787274 0.14432715 0.4266886 ]
 [0.90063068 0.1781515  0.82332576 0.67764476]
 [0.64408156 0.73563968 0.17913454 0.53985318]
 [0.18380692 0.50976698 0.58164198 0.35140542]
 [0.82434653 0.74328138 0.32731466 0.74017094]]


### b) randint -- given the random integer value between the range single value
#### syntax-- randint(starting,ending-1,no. of elements) 
#### by default 1 no. of elements

In [9]:
a=np.random.randint(12)
print(a)

10


In [10]:
# randint with reshape
a=np.random.randint(1,50,100).reshape(10,10)
print(a)

[[15  6 35  4 35 24 34  7 19 45]
 [48 30 32 42 12 31 44 30 20 22]
 [45 13  1 34 41 49 36 49 41 13]
 [33 38 13 47 16 19  5  2 47  6]
 [35 49 19  2 14 45 17 12 22 24]
 [28 37 34 42 44 25 24 46 11 34]
 [22  1 20  8 40 24 26 32 48 20]
 [11 26  3 17 43 44 31 17 20 31]
 [35 25 14 26 47 21 36 46 28  8]
 [46 21 20 39 43 22 39 40 28 33]]


In [12]:
# create a array of random integer numbers from 1 to 51 and reshape the array into posible formats
arr=np.random.randint(1,51,36)
print(arr.reshape(1,36))

[[36 46 30 12 25 42 33  7 30  5 44  8 49 41 17 26 11 22 28 16 22 21 17 36
  13 14 49 50 22 18  1 22 38 42 46 17]]


In [13]:
print(arr.reshape(36,1))

[[36]
 [46]
 [30]
 [12]
 [25]
 [42]
 [33]
 [ 7]
 [30]
 [ 5]
 [44]
 [ 8]
 [49]
 [41]
 [17]
 [26]
 [11]
 [22]
 [28]
 [16]
 [22]
 [21]
 [17]
 [36]
 [13]
 [14]
 [49]
 [50]
 [22]
 [18]
 [ 1]
 [22]
 [38]
 [42]
 [46]
 [17]]


In [14]:
print(arr.reshape(4,9))

[[36 46 30 12 25 42 33  7 30]
 [ 5 44  8 49 41 17 26 11 22]
 [28 16 22 21 17 36 13 14 49]
 [50 22 18  1 22 38 42 46 17]]


In [15]:
print(arr.reshape(3,12))

[[36 46 30 12 25 42 33  7 30  5 44  8]
 [49 41 17 26 11 22 28 16 22 21 17 36]
 [13 14 49 50 22 18  1 22 38 42 46 17]]


In [16]:
print(arr.reshape(6,6))

[[36 46 30 12 25 42]
 [33  7 30  5 44  8]
 [49 41 17 26 11 22]
 [28 16 22 21 17 36]
 [13 14 49 50 22 18]
 [ 1 22 38 42 46 17]]


In [17]:
print(arr.reshape(12,3))

[[36 46 30]
 [12 25 42]
 [33  7 30]
 [ 5 44  8]
 [49 41 17]
 [26 11 22]
 [28 16 22]
 [21 17 36]
 [13 14 49]
 [50 22 18]
 [ 1 22 38]
 [42 46 17]]


## 3) Zeros-- generates zero in float value
#### syntax --- zeros(4)

In [18]:
a=np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [19]:
# zeros with reshape
print(a.reshape(1,4))

[[0. 0. 0. 0.]]


In [22]:
# 2d array without using reshape
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# create a array of zeroes of matrix format   5,5 using first reshPE AND again without using reshape
arr=np.zeros(25).reshape(5,5)
print(arr)
print("Without reshape")
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Without reshape
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 4) Ones-- create array of 1 but floating value

In [34]:
arr=np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [31]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
print(arr.reshape(2,3))

[[1. 1. 1.]
 [1. 1. 1.]]


## How to create identity matrix


## 5) eye-- used to creaate identity matrix

In [1]:
import numpy as np

In [2]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## How to change float value to integer
## with the help of dtype

In [3]:
a=np.eye(4,dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### without reshaope matrix with randint

In [6]:
# np.random.randint(12,34,16)
np.random.randint(10,34,(3,4))

array([[28, 24, 20, 19],
       [13, 11, 31, 28],
       [28, 27, 23, 13]], dtype=int32)

In [7]:
np.ones((5,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Indexing
### syntax-- array_name[row_index,col_index]

In [24]:
arr=np.random.randint(12,90,(3,4))
print(arr)

[[69 38 21 37]
 [20 40 28 70]
 [73 25 65 17]]


In [15]:
print(arr[1,1])
print(arr[1,3])
print(arr[2,4])
arr[9,9]
arr[9,8]


83
22
47


np.int32(86)

### Boolean Indexing --- condition ke basis pr data ko filter krta hai --- syntax -- array_name[array_name> number]

In [18]:
print(arr)

[[52 21 88 12 17 81 71 77 43 44]
 [62 51 54 42 77 57 14 35 32 45]
 [34 57 52 33 59 28 17 23 73 12]
 [83 14 41 63 48 59 76 87 35 46]
 [54 67 45 75 18 34 70 37 29 89]
 [48 54 64 18 21 66 64 33 20 15]
 [77 77 12 30 32 50 27 42 45 74]
 [55 78 58 52 50 26 39 76 69 78]
 [41 73 80 63 58 58 48 62 32 28]
 [18 64 46 45 56 47 89 14 13 38]]


In [21]:
print(arr[arr>70])

[88 81 71 77 77 73 83 76 87 75 89 77 77 74 78 76 78 73 80 89]


In [22]:
print(arr[arr%2==0])

[52 88 12 44 62 54 42 14 32 34 52 28 12 14 48 76 46 54 18 34 70 48 54 64
 18 66 64 20 12 30 32 50 42 74 78 58 52 50 26 76 78 80 58 58 48 62 32 28
 18 64 46 56 14 38]


## Slicing
### syntax-- array_name[(row_start : row_start),(col_start :col_stop)]

In [25]:
print(arr)

[[69 38 21 37]
 [20 40 28 70]
 [73 25 65 17]]


In [28]:
print(arr[1:2,1:3])

[[40 28]]


In [29]:
print(arr[1: ,3:])

[[70]
 [17]]


In [31]:
print(arr[1:2,:])

[[20 40 28 70]]


In [32]:
print(arr[1:,:])

[[20 40 28 70]
 [73 25 65 17]]
