## homework task -12 sep

In [ ]:
# 1. create a array containing element 1 to 15
# 2. create a araay of mixed data types containing 4 elements and tell what datatype will change and why
# 3. on the above created array find the datatype of elements
# 4. create a array of size 7 and also print the size
# 5. create a array of 1st 5 even number and print size, datatype, total memory of array, shape of array,and which dimension is the array is and alsoo write one line definition what the attributes are doing

## homework task -16 sep

In [ ]:
#1. create a program 

## Practice


### 1.)Create a 1D NumPy array of the first 10 even numbers.


In [3]:
import numpy as np
arr = np.arange(0,20,2)
print("Array of first 10 even number is:",arr)

Array of first 10 even number is: [ 0  2  4  6  8 10 12 14 16 18]


### 2.)Create a 3x3 array of all zeros, then a 3x3 identity matrix.


In [9]:
zero=np.zeros((3,3),dtype=int)
print("3x3 Zero matrix is:")
print(zero)
identy = np.eye(3,dtype=int)
print("3x3 Identity matrix is:")
print(identy)

3x3 Zero matrix is:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
3x3 Identity matrix is:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 3.)Create np.arange(20), reshape it into a 4x5 array, and print its .ndim, .shape, and .size.


In [11]:
arr = np.arange(20).reshape(4,5)
print("Array is:")
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

Array is:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2
(4, 5)
20


### 4.)Create an array with mixed values [1, 2.5, 3] and print its dtype.


In [12]:
arr = np.array([1,2.5,3])
print(arr)
print(arr.dtype)

[1.  2.5 3. ]
float64


### 5.)Create a 1D array of 8 elements using np.linspace(0, 100, 8).


In [13]:
arr = np.linspace(0,100,8)
print(arr)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


### 6.)Generate 5 random integers between 50 and 100 using np.random.randint().


In [14]:
arr=np.random.randint(50,101,5)
print(arr)

[88 74 83 64 94]


### 7.)Create a (2,3) array of ones and check its .itemsize and total memory (itemsize * size).


In [19]:
arr=np.ones((2,3),dtype=int)
print(arr)
print(arr.itemsize)
print("Total size =", arr.itemsize* arr.size)

[[1 1 1]
 [1 1 1]]
8
Total size = 48


### 8.) Given arr = np.arange(1, 21).reshape(4,5), extract the 2nd and 3rd rows using slicing.


In [28]:
arr =np.arange(1,21).reshape(4,5)
print(arr)
print(arr[1:3 , :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]


### 9.) From a marks array [55, 67, 89, 32, 90, 41, 76], use boolean indexing to get marks that are ≥ 40 and < 85.


In [36]:
marks=np.array([55, 67, 89, 32, 90, 41, 76])
print(marks[ (marks>=45) & (marks<85)] )

[55 67 76]


### 10.) Use fancy indexing to select the elements at indices [1, 3, 5] from np.arange(10, 20).


### 11.) Create a (3,1) array and a (1,4) array, add them together using broadcasting, and print the result's shape.


### 12.) Given a (4,4) array of np.arange(16).reshape(4,4), print its transpose.


In [37]:
ar=np.arange(16).reshape(4,4)
print(ar)
print()
print()
print("Transpose is")
print(ar.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Transpose is
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


### 13.) Create a (2,3) array and produce both its .flatten() and .ravel() versions, then modify the raveled version's first element and print the original array.


In [41]:
ar=np.random.randint(12,50,(2,3))
print(ar)
rav=ar.ravel()
rav[0]=2345
print("Original Array:")
print(ar)
print("Array after ravel:")
print(rav)


[[39 22 26]
 [24 43 39]]
Original Array:
[[2345   22   26]
 [  24   43   39]]
Array after ravel:
[2345   22   26   24   43   39]


In [42]:
ar=np.random.randint(12,50,(2,3))
print(ar)
flat=ar.flatten()
flat[0]=2345
print("Original Array:")
print(ar)
print("Array after ravel:")
print(flat)

[[31 31 37]
 [22 36 30]]
Original Array:
[[31 31 37]
 [22 36 30]]
Array after ravel:
[2345   31   37   22   36   30]


### 14.) Given arr = np.arange(1, 13), reshape it to (3,4) and then use .reshape(-1) to flatten it back to 1D.


In [43]:
arr=np.arange(1,13).reshape(3,4)
print(arr)
arr1=arr.reshape(-1)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### 15. Iterate through a (2,3) 2D array using np.nditer()

In [44]:
arr=np.random.randint(10,40,(2,3))
print(arr)
for i in np.nditer(arr):
    print(i)

[[24 37 15]
 [33 34 15]]
24
37
15
33
34
15


## Practice2

### Q1. Replace all odd numbers in the given array with -1
#### input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#### expected Output->[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]



In [3]:
import numpy as np
input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.where(input %2 != 0, -1,input))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Q2. Convert a 1-D array into a 2-D array with 3 rows
#### input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]) output = [[ 0, 1, 2],[3, 4, 5],[6, 7, 8]]



In [4]:
input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(input.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Q3. Create a 2-D array with 202 to all the values
#### Output = [[202, 202],[202, 202]]



In [5]:
print(np.full((4,3),202))

[[202 202 202]
 [202 202 202]
 [202 202 202]
 [202 202 202]]


### Q4. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
#### output = [36, 30, 36, 38, 31, 35, 36, 30, 32, 34]



In [7]:
arr=np.random.randint(30,41,10)
print(arr)

[33 36 38 35 34 32 30 32 38 32]


### Q.6 Create a null vector of size 10
#### output = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]



In [9]:
arr=np.zeros(10,dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


### Q.7 Create a null vector of size 10 but the fifth value which is 1
#### output = [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]



In [15]:
arr = np.zeros(10,dtype=int)
arr[4]=1
print(arr)

[0 0 0 0 1 0 0 0 0 0]


### Q.8 Reverse a vector (first element becomes last)



In [27]:
arr = np.arange(10,21)
print(arr)
print(arr[ : : -1])

[10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10]


### Q.9 Create a 3x3 identity matrix



In [29]:
arr=np.eye(3,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Q.11 Create a 10x10 array with random values and find the minimum and maximum values



In [31]:
arr=np.random.randint(10,40,(10,10))
print(arr)
print()
print("Minimum:",arr.min())
print("Maximum:",arr.max())

[[34 18 35 35 32 39 21 22 17 28]
 [35 25 20 25 37 22 21 23 33 33]
 [31 22 31 39 26 14 18 11 34 18]
 [23 27 24 14 24 33 11 38 33 19]
 [16 29 35 37 30 27 23 35 34 15]
 [37 23 21 39 18 32 32 19 39 38]
 [27 13 18 23 16 30 13 29 13 21]
 [32 24 23 14 22 31 13 34 15 22]
 [34 36 36 26 17 10 21 17 19 19]
 [38 25 22 24 24 28 38 23 37 22]]

Minimum: 10
Maximum: 39


### Q.16 How to convert a float (32 bits) array into an integer (32 bits) in place?



### Q.13 Create a 2d array with 1 on the border and 0 inside

In [36]:
arr=np.ones((4,4),dtype=int)
arr[1:3,1:3]=0
print(arr)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


## PRACTICE 3

#### 1. Create a 1D array of numbers from 50 to 100 with a step of 5.


In [6]:
import numpy as np
arr=np.linspace(50,100,11,dtype=int)
print(arr)

[ 50  55  60  65  70  75  80  85  90  95 100]


#### 2. Given arr = np.array([[4,8],[15,16]]), print its .dtype and convert it to float32.


In [10]:
arr = np.array([[4,8],[15,16]])
print(arr.dtype)
arr = np.array([[4,8],[15,16]],dtype=float)
print(arr.dtype)




int64
float64


#### 3. Create a (3,3) array of random integers between 1-9 and print its transpose.


In [13]:
arr=np.random.randint(1,10,(3,3))
print(arr)
print("Transpose")
print(arr.T)

[[8 9 5]
 [8 9 2]
 [2 2 5]]
Transpose
[[8 8 2]
 [9 9 2]
 [5 2 5]]


#### 4. Given arr = np.arange(30).reshape(5,6), extract the last 2 columns using slicing.


In [14]:
arr = np.arange(30).reshape(5,6)
print(arr)
print("Last two column:")
print(arr[ : , 4: ])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Last two column:
[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]]


#### 5. Use boolean indexing on np.array([12,45,7,89,23,56]) to get all values divisible by 3.


In [15]:
arr=np.array([12,45,7,89,23,56])
print(arr[arr%3==0])

[12 45]


#### 6. Given A = np.array([[2,1],[1,3]]) and B = np.array([[1,0],[0,1]]), compute A @ B.


In [16]:
A = np.array([[2,1],[1,3]])
B = np.array([[1,0],[0,1]])
print(A@B)

[[2 1]
 [1 3]]


#### 7. Set np.random.seed(15) and generate a (3,3) array of random integers 1-20.


#### 8. Given marks = np.array([56,78,92,34,88,67,45]), compute mean, median, and standard
deviation.


In [ ]:
9. Given a (4,5) array of random integers, find the sum of each row and each column separately
using axis.


#### 10. Create a (2,4) array and use .flatten() and .ravel() — modify each result and observe which
#### one changes the original array.


In [19]:
arr=np.arange(1,9).reshape(2,4)
print(arr)
flat=arr.flatten()
flat[0]=2345
print("Flatten array:")
print(flat)
print("Array after flatten:")
print(arr)
rav=arr.ravel()
rav[0]= 9877
print("Ravel array:")
print(rav)
print("Array after Ravel:")
print(arr)



[[1 2 3 4]
 [5 6 7 8]]
Flatten array:
[2345    2    3    4    5    6    7    8]
Array after flatten:
[[1 2 3 4]
 [5 6 7 8]]
Ravel array:
[9877    2    3    4    5    6    7    8]
Array after Ravel:
[[9877    2    3    4]
 [   5    6    7    8]]


#### 11. Given temps = np.array([98.6, 101.2, 97.4, 103.5, 99.1]), label each as "Fever" if above 100,
#### else "Normal".


In [24]:
temps = np.array([98.6, 101.2, 97.4, 103.5, 99.1])
print(np.where(temps>100,'FEVER','NORMAL'))

['NORMAL' 'FEVER' 'NORMAL' 'FEVER' 'NORMAL']


#### 12. Given arr = np.array([5,12,8,25,3,19]), find the 2nd smallest value without using a loop.


In [30]:
arr = np.array([5,12,8,25,3,19])
sor=np.sort(arr)
# le=arr.len()

print(sor)
print("Seond max:",sor[-1-1])

[ 3  5  8 12 19 25]
Seond max: 19


#### 14. Given a = np.array([1,2,3]) and b = np.array([[1],[2],[3]]), predict and verify the shape of a *
#### b.


In [32]:
a = np.array([1,2,3]) 
b = np.array([[1],[2],[3]])
print((a*b).shape)


(3, 3)


#### 15. Create an array of 15 random integers between 1-100, then use np.unique() 


In [33]:
arr=np.random.randint(1,100,15)
print(arr)
print("Unique:")
print(np.unique(arr))

[17 87 97 57 55 75  6 45  7 48 23 63  1 58 36]
Unique:
[ 1  6  7 17 23 36 45 48 55 57 58 63 75 87 97]


#### 16. Given prices = np.array([199,450,89,999,320]), use np.clip() to cap all prices between 100
and 500.